// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeByStupid","Show Custom Splash":"true","Custom Image":"RPGBreaker","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}}
];
